// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/mongo/mongo.go
//
// Generated by this command:
//
//	mockgen -source=pkg/storage/mongo/mongo.go -destination=internal/mocks/mock_mongo_datastore.go -package=mocks MongoDatastore
//

// Package mocks is a generated GoMock package.
package mocks
